# A basic Job definition
apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    spec:
      containers:
      - name: job
        image: busybox
        command: ["echo", "Hello from the Job"]
      restartPolicy: Never
  backoffLimit: 4
